#!/bin/sh

bright=$(lux -G | sed 's/%//') 

case 1 in
	$((bright >= 80)) ) icon=" " ;;
	$((bright >= 60)) ) icon=" " ;;
	$((bright >= 40)) )  icon=" " ;;
	$((bright >= 0)) )  icon=" " ;;
	* ) echo  && exit ;;
esac

echo "$icon $bright%"
